version: '3.8'

services:
  dropfeedback_db:
    restart: always
    image: postgres:14.1-alpine
    container_name: dropfeedback_db
    environment:
      POSTGRES_DB: dropfeedback_db
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_PORT: 5432
    ports:
      - '5432:5432'
    volumes:
      - dropfeedback_db:/var/lib/postgresql/data
    networks:
      - postgres
  test_db:
    restart: always
    image: postgres:14.1-alpine
    container_name: test_db
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_PORT: 5432
    ports:
      - '5434:5432'
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  dropfeedback_db:
