# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: API e2e test

on:
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/api

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3

      - uses: isbang/compose-action@v1.5.1
        with:
          down-flags: "--volumes"
          compose-file: "../../docker-compose.yml"

      - run: echo $(docker container ls --format "table {{.ID}}\t{{.Names}}\t{{.Ports}}" -a)

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: cp .env.test .env

      - run: npm ci
      - run: npx prisma migrate reset --force
      - run: npm run build
      - run: npm run test:e2e
